/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:501f1615-60f1-443e-8c1e-163bf322e096",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_POl7qYuUi",
    "aws_user_pools_web_client_id": "1an1cnv9643hsk09j9n5rpbuk8",
    "oauth": {}
};


export default awsmobile;
